name: Mat CI


on:
  push:
    branches: [ "main" ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v2 
      
    - name: Set up Node.js 
      uses: actions/setup-node@v2 
      with:
        node-version: '16' # specify your Node.js version 
        
    - name: Install dependencies 
      run: npm install 
      
    - name: Build project 
      run: npm run build # or your specific build command
    

    - run: tar -czf build.tar.gz dist

    - name: Upload build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build.tar.gz


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with: 
       name: artifact
       path: dist/

    - name: Deploy via SSH
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        scp -i ~/.ssh/id_rsa -P ${{ secrets.SSH_PORT }} dist/build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ec2-user/venu

        ssh -i ~/.ssh/id_rsa -p ${{ secretrs.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ec2-user/venu
          tar -xzf build.tar.gz
          mv build/* .
        EOF
